### ISSUE TITLE
Outputting zoomed in PNG

### ISSUE THREAD

**Issue by lifflander** [DARMA-tasking/LB-analysis-framework#45] opened 2019-12-09 21:08 UTC
`python ./src/Applications/NodeGossiper.py -o 128 -x 8 -y 8 -z 1 -t uniform,1.0,10.0 -w uniform,1.0,10.0  -k 5 -f 2 -i 3 -p 10   -c 2 -d 3 -e`

```diff
diff --git a/src/Applications/AnimationViewer.py b/src/Applications/AnimationViewer.py
index ba0dd03..3860279 100644
--- a/src/Applications/AnimationViewer.py
+++ b/src/Applications/AnimationViewer.py
@@ -50,7 +50,7 @@ class AnimationViewer(ParaviewViewer):
         super(AnimationViewer, self).__init__(exodus, file_name, viewer_type)

     ###########################################################################
-    def saveView(self, reader):
+    def saveView(self, reader, view):
         """Save animation
         """

@@ -67,11 +67,14 @@ class AnimationViewer(ParaviewViewer):
             + "[AnimationViewer] "
             + bcolors.END
             + "###  Generating AVI animation...")
-        pv.WriteAnimation(self.file_name+".avi",
-                       Magnification=1,
-                       Quality = 2,
-                       FrameRate=1.0,
-                       Compression=True)
+        filename = "{}.avi".format(self.file_name)
+        pv.SaveAnimation(filename)
+        # pv.WriteAnimation(self.file_name+".avi",
+        #                Magnification=1,
+        #                Quality = 2,
+        #                viewOrLayout=view,
+        #                FrameRate=1.0,
+        #                Compression=True)
```

![True e 0 000000](https://user-images.githubusercontent.com/3324465/70472873-c1580d80-1a84-11ea-86c1-3fef594e5766.png)
![True e 1 000000](https://user-images.githubusercontent.com/3324465/70472875-c1580d80-1a84-11ea-86ee-127712211cd8.png)
![True e 2 000000](https://user-images.githubusercontent.com/3324465/70472876-c1f0a400-1a84-11ea-9d10-46b9aa278b08.png)
![True e 3 000000](https://user-images.githubusercontent.com/3324465/70472877-c1f0a400-1a84-11ea-9198-45bd91cae6bf.png)

**Comment by ppebay** [comment] 2021-11-17 11:53
@lifflander are you still seeing the same issue?

It seems that the problem is resolved

**Comment by ppebay** [comment] 2022-06-18 17:57
Closing resolved issue

**Closed by ppebay** 2022-06-18 17:57 UTC
